name: Trigger auto deployment for album-app2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/album-app2-AutoDeployTrigger-3a4ced28-3197-4c81-8ef3-aaf18a32c502.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ALBUMAPP2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ALBUMAPP2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALBUMAPP2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.ALBUMAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMAPP2_REGISTRY_PASSWORD }}
          containerAppName: album-app2
          resourceGroup: meeting-demo
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


