name: Trigger auto deployment for demo-app3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-app3-AutoDeployTrigger-493b0486-fd05-467b-b506-5dd2a620153d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEMOAPP3_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOAPP3_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOAPP3_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.DEMOAPP3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOAPP3_REGISTRY_PASSWORD }}
          containerAppName: demo-app3
          resourceGroup: artifact-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


