name: Trigger auto deployment for tests2cdotnet

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tests2cdotnet-AutoDeployTrigger-827ee439-c894-4845-9d17-0087ebb43b85.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTS2CDOTNET_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTS2CDOTNET_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTS2CDOTNET_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TESTS2CDOTNET_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTS2CDOTNET_REGISTRY_PASSWORD }}
          containerAppName: tests2cdotnet
          resourceGroup: tmauldin-test
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


